export const football_keywords = [
  "football",
  "soccer",
  "match",
  "game",
  "team",
  "club",
  "player",
  "signing",
  "transfer",
  "contract",
  "injury",
  "injured",
  "recovery",
  "starting lineup",
  "squad",
  "manager",
  "coach",
  "goal",
  "score",
  "victory",
  "defeat",
  "draw",
  "stadium",
  "fans",
  "supporters",
  "league",
  "tournament",
  "championship",
  "title",
  "captain",
  "substitute",
  "penalty",
  "red card",
  "yellow card",
  "referee",
  "VAR",
  "training",
  "preseason",
  "post-match",
  "press conference",
  "tactics",
  "formation",
  "midfielder",
  "defender",
  "forward",
  "striker",
  "goalkeeper",
  "corner kick",
  "free kick",
  "offside",
  "dribble",
  "tackle",
  "pass",
  "assist",
  "penalty shootout",
  "fixture",
  "schedule",
  "result",
  "table",
  "standings",
  "fanbase",
  "rivalry",
  "champion",
  "promotion",
  "relegation",
  "substitution",
  "hat-trick",
  "own goal",
  "premier league",
  "La Liga",
  "Serie A",
  "Bundesliga",
  "Ligue 1",
  "UEFA Champions League",
  "Europa League",
  "World Cup",
  "continental cup",
  "friendly match",
  "FA Cup",
  "EFL Cup",
  "Copa del Rey",
  "DFB-Pokal",
  "Coupe de France",
  "national team",
  "international",
  "friendly",
  "transfer window",
  "loan",
  "youth academy",
  "scouting",
  "ownership",
  "financial",
  "relegation",
  "promotion",
];
export const premier_league_teams = [
  "Arsenal",
  "Aston Villa",
  "Brentford",
  "Brighton & Hove Albion",
  "Burnley",
  "Chelsea",
  "Crystal Palace",
  "Everton",
  "Leeds United",
  "Leicester City",
  "Liverpool",
  "Manchester City",
  "Manchester United",
  "Newcastle United",
  "Norwich City",
  "Southampton",
  "Tottenham Hotspur",
  "Watford",
  "West Ham United",
  "Wolverhampton Wanderers",
];

//  La Liga Teams
export const la_liga_teams = [
  "Alavés",
  "Athletic Bilbao",
  "Atlético Madrid",
  "Barcelona",
  "Cádiz",
  "Celta Vigo",
  "Elche",
  "Espanyol",
  "Getafe",
  "Granada",
  "Levante",
  "Mallorca",
  "Osasuna",
  "Rayo Vallecano",
  "Real Betis",
  "Real Madrid",
  "Real Sociedad",
  "Sevilla",
  "Valencia",
  "Villarreal",
];

// Bundesliga Teams
export const bundesliga_teams = [
  "Arminia Bielefeld",
  "Augsburg",
  "Bayer Leverkusen",
  "Bayern Munich",
  "Bochum",
  "Borussia Dortmund",
  "Borussia Mönchengladbach",
  "Cologne",
  "Eintracht Frankfurt",
  "Freiburg",
  "Greuther Fürth",
  "Hertha BSC",
  "Mainz 05",
  "RB Leipzig",
  "Stuttgart",
  "Union Berlin",
  "VfL Wolfsburg",
  "Werder Bremen",
];
export const footballTeams = [
  ...premier_league_teams,
  ...la_liga_teams,
  ...bundesliga_teams,
];
export const allKeywords = [...football_keywords, ...footballTeams];
